#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Build the 3SF guest driver (driver.c) and regenerate src/rip/driver_blob.h.

Needs clang and ld.lld with the ARM target, and llvm-objcopy and llvm-nm. It's only needed when
driver.c changes: the generated file is committed, so building 3SF itself needs no ARM toolchain.
"""
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUTPUT = HERE.parent / "src" / "rip" / "driver_blob.h"
BASE = 0x0E000000

CFLAGS = [
    "--target=armv6k-none-eabihf", "-mcpu=mpcore", "-marm", "-mfloat-abi=hard", "-mfpu=vfpv2",
    "-Os", "-ffreestanding", "-fno-builtin", "-nostdlib", "-fno-pic", "-fno-exceptions", "-fno-unwind-tables",
    "-fno-asynchronous-unwind-tables", "-Wall", "-Wextra",
]


def render_header(blob, entry, params, end):
    """Returns driver_blob.h for a linked driver image, formatted to match clang-format."""
    lines = [
        "// SPDX-License-Identifier: MIT",
        "",
        "// Generated by driver/build.py from driver/driver.c; do not edit.",
        "// The 3SF guest driver, loaded at 0x0E000000.",
        "",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace threesf::rip",
        "{",
        "",
        "inline constexpr uint32_t kDriverBase = 0x%08x;" % BASE,
        "inline constexpr uint32_t kDriverEntry = 0x%08x;" % entry,
        "inline constexpr uint32_t kDriverParams = 0x%08x;" % params,
        "inline constexpr uint32_t kDriverEnd = 0x%08x; // the end of the bss" % end,
        "inline constexpr uint8_t kDriverBlob[] = {",
    ]
    for i in range(0, len(blob), 19):
        lines.append("    " + ", ".join("0x%02x" % b for b in blob[i:i + 19]) + ",")
    lines += ["};", "", "} // namespace threesf::rip"]
    return "\n".join(lines) + "\n"


def symbol_address(nm_output, name):
    for line in nm_output.splitlines():
        fields = line.split()
        if len(fields) == 3 and fields[2] == name:
            return int(fields[0], 16)
    sys.exit(f"error: {name} isn't in the linked driver")


def main():
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp)
        obj, elf, binary = out / "driver.o", out / "driver.elf", out / "driver.bin"
        subprocess.run(["clang", *CFLAGS, "-c", str(HERE / "driver.c"), "-o", str(obj)], check=True)
        subprocess.run(["ld.lld", "-T", str(HERE / "driver.ld"), "--no-dynamic-linker", "-o", str(elf), str(obj)],
                       check=True)
        subprocess.run(["llvm-objcopy", "-O", "binary", str(elf), str(binary)], check=True)
        symbols = subprocess.run(["llvm-nm", str(elf)], check=True, capture_output=True, encoding="utf-8").stdout
        blob = binary.read_bytes()

    entry = symbol_address(symbols, "driver_entry")
    params = symbol_address(symbols, "driver_params")
    end = symbol_address(symbols, "driver_end")
    OUTPUT.write_text(render_header(blob, entry, params, end), encoding="utf-8", newline="\n")
    print(f"driver: {len(blob)} bytes, entry 0x{entry:08x}, params 0x{params:08x}, bss end 0x{end:08x}")


if __name__ == "__main__":
    main()
